version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
  exclusions:
    rules:
      - path-except: '^/examples/'
        linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
          - gocritic

run:
  timeout: 5m
  tests: true
