// Command orchestrator-migrate-gen generates SQL migration files for the orchestrator.
//
// Usage:
//
//	go run github.com/getpup/pupsourcing-orchestrator/cmd/orchestrator-migrate-gen -output migrations -filename orchestrator_init.sql
//
// Or with go generate:
//
//	//go:generate go run github.com/getpup/pupsourcing-orchestrator/cmd/orchestrator-migrate-gen -output migrations
//
// Generate migrations with custom table names:
//
//	go run github.com/getpup/pupsourcing-orchestrator/cmd/orchestrator-migrate-gen -generations-table my_generations -workers-table my_workers
//
// The down migration is optional and not generated by default. Use -generate-down to include it:
//
//	go run github.com/getpup/pupsourcing-orchestrator/cmd/orchestrator-migrate-gen -generate-down
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/getpup/pupsourcing-orchestrator/store/postgres"
)

func main() {
	var (
		outputFolder     = flag.String("output", "migrations", "Output folder for migration file")
		outputFilename   = flag.String("filename", "", "Output filename (default: timestamp-based)")
		generationsTable = flag.String("generations-table", "orchestrator_generations", "Name of generations table")
		workersTable     = flag.String("workers-table", "orchestrator_workers", "Name of workers table")
		generateDown     = flag.Bool("generate-down", false, "Generate down migration (optional)")
	)

	flag.Parse()

	config := postgres.TableConfig{
		GenerationsTable: *generationsTable,
		WorkersTable:     *workersTable,
	}

	// Generate filename if not provided
	filename := *outputFilename
	if filename == "" {
		timestamp := time.Now().Format("20060102150405")
		filename = fmt.Sprintf("%s_orchestrator_init.sql", timestamp)
	}

	// Ensure output directory exists
	if err := os.MkdirAll(*outputFolder, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output directory: %v\n", err)
		os.Exit(1)
	}

	// Generate up migration
	upFilePath := filepath.Join(*outputFolder, filename)
	upSQL := postgres.MigrationUp(config)
	if err := os.WriteFile(upFilePath, []byte(upSQL), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing up migration: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated up migration: %s\n", upFilePath)

	// Generate down migration if requested
	if *generateDown {
		ext := filepath.Ext(filename)
		var downFilename string
		if ext != "" {
			downFilename = filename[:len(filename)-len(ext)] + ".down" + ext
		} else {
			downFilename = filename + ".down"
		}

		downFilePath := filepath.Join(*outputFolder, downFilename)
		downSQL := postgres.MigrationDown(config)
		if err := os.WriteFile(downFilePath, []byte(downSQL), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing down migration: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Generated down migration: %s\n", downFilePath)
	}
}
